spring:
  cloud:
    azure:
      cosmos:
        database: ${COSMOS_DATABASE_NAME}
        key: ${COSMOS_KEy}
        endpoint: ${COSMOS_ENDPOINT}
      keyvault:
        secret:
          property-source-enabled: false
          enabled: false
          endpoint: ${KEY_VAULT_URI}
        certificate:
          enabled: false
          endpoint: ${KEY_VAULT_URI}
      eventhubs:
        consumer:
          consumer-group: ${EVENTHUBS_CONSUMER_GROUP_NAME}
        event-hub-name: ${EVENTHUBS_EVENTHUB_NAME}
        namespace: ${EVENTHUBS_NAMESPACE_NAME}
        connection-string: ${EVENTHUBS_CONNECTION_STRING}
      servicebus:
        producer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        consumer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        namespace: ${SERVICEBUS_NAMESPACE_NAME}
        connection-string: ${SERVICEBUS_CONNECTION_STRING}
      storage:
        blob:
          account-key: ${STORAGE_ACCOUNT_KEY}
          account-name: ${STORAGE_ACCOUNT_NAME}
          container-name: ${STORAGE_CONTAINER_NAME}
          blob-name: ${blob-name}
        fileshare:
          account-key: ${STORAGE_ACCOUNT_KEY}
          account-name: ${STORAGE_ACCOUNT_NAME}
          share-name: ${STORAGE_SHARE_NAME}
          file-name: ${file-name}
        queue:
          account-key: ${STORAGE_ACCOUNT_KEY}
          account-name: ${STORAGE_ACCOUNT_NAME}
management:
  endpoint:
    health:
      show-details: always
  health:
    azure-cosmos:
      enabled: true
