# output "application_hostname" {
#   value       = module.application.application_hostname
#   description = "The Web application URL."
# }

output "resource_group" {
  value       = azurecaf_name.resource_group.name
  description = "The resource group."
}

# output "application_caf_name" {
#   value       = module.application.application_caf_name
#   description = "The application name generated by the Azure Cloud Adoption Framework."
# }

# cosmos module
output "cosmos_endpoint" {
  value       = module.cosmos.cosmos_endpoint
  description = "The Azure Cosmos DB endpoint."
}

output "cosmos_database_name" {
  value       = module.cosmos.cosmos_database_name
  description = "The Azure Cosmos DB sql database name."
}

output "cosmos_key" {
  value       = module.cosmos.cosmos_key
  sensitive   = true
  description = "The Azure Cosmos DB primary key."
}

# event-hubs module
output "eventhubs_namespace_name" {
  value       = module.event-hubs.eventhubs_namespace_name
  description = "The Azure Event Hubs namespace name."
}

output "eventhubs_eventhub_name" {
  value       = module.event-hubs.eventhubs_eventhub_name
  description = "The Azure Event Hubs event hub name."
}

output "eventhubs_consumer_group_name" {
  value       = module.event-hubs.eventhubs_consumer_group_name
  description = "The Azure Event Hubs event hub consumer group name."
}

output "eventhubs_connection_string" {
  value       = module.event-hubs.eventhubs_connection_string
  sensitive   = true
  description = "The Azure Event Hubs namespace primary connection string."
}

# key-vault module
output "key_vault_uri" {
  value       = module.key-vault.key_vault_uri
  description = "The Azure Key Vault URI"
}

output "key_vault_secret_name" {
  value       = module.key-vault.key_vault_secret_name
  description = "The Azure Key Vault secret name"
}

# service-bus module
output "servicebus_namespace_name" {
  value       = module.service-bus.servicebus_namespace_name
  description = "The Azure Service Bus namespace name."
}

output "servicebus_queue_name" {
  value       = module.service-bus.servicebus_queue_name
  description = "The Azure Service Bus queue name."
}

output "servicebus_topic_name" {
  value       = module.service-bus.servicebus_topic_name
  description = "The Azure Service Bus topic name."
}

output "servicebus_subscription_name" {
  value       = module.service-bus.servicebus_subscription_name
  description = "The Azure Service Bus subscription name."
}

output "servicebus_connection_string" {
  value       = module.service-bus.servicebus_connection_string
  sensitive   = true
  description = "The Azure Service Bus namespace primary connection string."
}

# storage module
output "storage_account_name" {
  value       = module.storage.storage_account_name
  description = "The Azure Blob storage account name."
}

output "storage_account_key" {
  value       = module.storage.storage_account_key
  sensitive   = true
  description = "The Azure Blob storage access key."
}

output "storage_blob_endpoint" {
  value       = module.storage.storage_blob_endpoint
  description = "The Azure Blob storage endpoint."
}

output "storage_container_name" {
  value       = module.storage.storage_container_name
  description = "The Azure Storage blob container name."
}

output "storage_share_name" {
  value       = module.storage.storage_share_name
  description = "The Azure Storage file share name."
}

output "storage_queue_name" {
  value       = module.storage.storage_queue_name
  description = "The Azure Storage queue name."
}