spring:
  cloud:
    azure:
      credential:
        client-id: ${SPRING_CLIENT_ID}
        client-secret: ${SPRING_CLIENT_SECRET}
      profile:
        tenant-id: ${SPRING_TENANT_ID}
      cosmos:
        enabled: true
      keyvault:
        secret:
          enabled: true
        certificate:
          enabled: false
      eventhubs:
        enabled: true
      servicebus:
        enabled: true
      storage:
        blob:
          enabled: true
        fileshare:
          enabled: false
        queue:
          enabled: true

