spring:
  cloud:
    azure:
      credential:
        client-id: ${SPRING_CLIENT_ID}
        client-secret: ${SPRING_CLIENT_SECRET}
      profile:
        tenant-id: ${SPRING_TENANT_ID}
      cosmos:
        database: ${COSMOS_DATABASE_NAME}
        endpoint: ${COSMOS_ENDPOINT}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${KEY_VAULT_URI}
        certificate:
          enabled: false
          endpoint: ${KEY_VAULT_URI}
      eventhubs:
        consumer:
          consumer-group: ${EVENTHUBS_CONSUMER_GROUP_NAME}
        event-hub-name: ${EVENTHUBS_EVENTHUB_NAME}
        namespace: ${EVENTHUBS_NAMESPACE_NAME}
      servicebus:
        producer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        consumer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        namespace: ${SERVICEBUS_NAMESPACE_NAME}
      storage:
        blob:
          account-name: ${STORAGE_ACCOUNT_NAME}
          container-name: ${STORAGE_CONTAINER_NAME}
        fileshare:
          enabled: false
