spring:
  cloud:
    azure:
      cosmos:
        enabled: true
        key: ${COSMOS_KEY}
      keyvault:
        secret:
          enabled: true
        certificate:
          enabled: false
      eventhubs:
        enabled: true
        connection-string: ${EVENTHUBS_CONNECTION_STRING}
      servicebus:
        connection-string: ${SERVICEBUS_CONNECTION_STRING}
      storage:
        blob:
          account-key: ${STORAGE_ACCOUNT_KEY}
        fileshare:
          account-key: ${STORAGE_ACCOUNT_KEY}
        queue:
          account-key: ${STORAGE_ACCOUNT_KEY}
